# Generated by Django 5.0.3

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('especes', 'Espèces'), ('carte', 'Carte bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.user')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WavePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('payment_token', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wave_payment', to='payments.payment')),
            ],
            options={
                'db_table': 'wave_payments',
            },
        ),
        migrations.CreateModel(
            name='OrangeMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('otp', models.CharField(blank=True, max_length=10)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orange_payment', to='payments.payment')),
            ],
            options={
                'db_table': 'orange_money_payments',
            },
        ),
    ]
