# Generated by Django 5.0.3 on 2026-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('acompte', 'Acompte'), ('solde', 'Solde'), ('total', 'Paiement total')], default='acompte', help_text='Type de paiement (acompte, solde ou total)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='methode',
            field=models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('en_attente', 'Méthode non choisie')], max_length=20),
        ),
    ]
