# Generated by Django 5.0.3 on 2026-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litiges', '0003_fix_missing_gestionnaire_column'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='litige',
            new_name='litiges_statut_aeeb62_idx',
            old_name='litiges_statut_created_idx',
        ),
        migrations.RenameIndex(
            model_name='litige',
            new_name='litiges_client__890c24_idx',
            old_name='litiges_client_created_idx',
        ),
        migrations.RenameIndex(
            model_name='litige',
            new_name='litiges_gestion_a59f4a_idx',
            old_name='litiges_gestionnaire_idx',
        ),
        migrations.RenameIndex(
            model_name='litige',
            new_name='litiges_priorit_531603_idx',
            old_name='litiges_priorite_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='messagelitige',
            new_name='messages_li_litige__68476a_idx',
            old_name='msg_litige_created_idx',
        ),
        migrations.AlterField(
            model_name='litige',
            name='niveau_escalade',
            field=models.CharField(choices=[('client', 'Niveau client'), ('gestionnaire', 'Niveau gestionnaire'), ('admin', 'Niveau administration')], default='client', help_text="Niveau actuel d'escalade du litige", max_length=20),
        ),
        migrations.AlterField(
            model_name='litige',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('escalade', 'Escaladé'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', help_text='Statut actuel du litige', max_length=20),
        ),
    ]
