# Generated by Django 5.0.3 on 2026-03-05 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('terrains', '0002_terrainsynthetiquesdakar_capacite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jour_semaine', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_actif', models.BooleanField(default=True)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='terrains.terrainsynthetiquesdakar')),
            ],
            options={
                'db_table': 'creneaux_reservation',
                'ordering': ['jour_semaine', 'heure_debut'],
                'unique_together': {('terrain', 'jour_semaine', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('est_disponible', models.BooleanField(default=True)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='terrains.terrainsynthetiquesdakar')),
            ],
            options={
                'db_table': 'disponibilites',
                'indexes': [models.Index(fields=['terrain', 'date'], name='disponibili_terrain_f4af44_idx')],
                'unique_together': {('terrain', 'date', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_heures', models.PositiveIntegerField(help_text='Durée en heures', validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('en_cours', 'En cours')], default='en_attente', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('qr_code_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('qr_code_path', models.CharField(blank=True, max_length=255)),
                ('code_ticket', models.CharField(blank=True, max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='payments.payment')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='terrains.terrainsynthetiquesdakar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['terrain', 'date_debut'], name='reservation_terrain_fb4f60_idx'), models.Index(fields=['user', '-created_at'], name='reservation_user_id_c22ed0_idx'), models.Index(fields=['statut'], name='reservation_statut_d20d98_idx'), models.Index(fields=['qr_code_token'], name='reservation_qr_code_93c060_idx')],
            },
        ),
    ]
