# Generated by Django 5.0.3 on 2026-03-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_add_acompte_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='resa_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='resa_statut_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='resa_terrain_dates_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='resa_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='resa_qr_idx',
        ),
    ]
