# Generated by Django 5.0.3 on 2026-03-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_resa_dates_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('acompte_paye', 'Acompte payé - Solde à payer'), ('confirmee', 'Confirmée (entièrement payée)'), ('annulee', 'Annulée'), ('terminee', 'Terminée'), ('en_cours', 'En cours')], default='en_attente', max_length=30),
        ),
    ]
