# Generated by Django 5.0.3 on 2026-03-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('client', 'Client')], default='client', max_length=20)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('nom_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_ninea', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_registre_commerce', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('documents_legaux', models.JSONField(blank=True, null=True)),
                ('taux_commission_defaut', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_payment_link', models.URLField(blank=True, help_text='Lien Wave Business pour recevoir des paiements', null=True)),
                ('wave_contact_label', models.CharField(blank=True, help_text='Nom/description du compte Wave (ex: Ch Tech Business)', max_length=255, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
