# Generated by Django 5.0.3 on 2026-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loyalty_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyaccount',
            name='parrain',
        ),
        migrations.RemoveField(
            model_name='loyaltyaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loyaltytransaction',
            name='loyalty_account',
        ),
        migrations.RemoveField(
            model_name='loyaltyredemption',
            name='loyalty_account',
        ),
        migrations.DeleteModel(
            name='LoyaltyConfig',
        ),
        migrations.RemoveField(
            model_name='loyaltyredemption',
            name='reward',
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='UID Firebase pour les utilisateurs Google', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur s'est inscrit via Google"),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL de la photo de profil (Google)', null=True),
        ),
        migrations.DeleteModel(
            name='LoyaltyTransaction',
        ),
        migrations.DeleteModel(
            name='LoyaltyAccount',
        ),
        migrations.DeleteModel(
            name='LoyaltyRedemption',
        ),
        migrations.DeleteModel(
            name='LoyaltyReward',
        ),
    ]
