# Generated by Django 5.0.3 on 2026-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='capacite',
            field=models.PositiveIntegerField(blank=True, help_text='Capacité maximale du terrain', null=True),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='prix_heure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix par heure en FCFA', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
