# Generated by Django 5.0.3 on 2026-03-16 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0006_merge_20260312_0000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeabonnement',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date de début souhaitée', null=True),
        ),
        migrations.AddField(
            model_name='demandeabonnement',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin prévue', null=True),
        ),
        migrations.AddField(
            model_name='demandeabonnement',
            name='montant_acompte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant acompte pour paiement par match', max_digits=10),
        ),
        migrations.AddField(
            model_name='demandeabonnement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payé à date', max_digits=10),
        ),
        migrations.AddField(
            model_name='demandeabonnement',
            name='nb_seances_payees',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de séances payées'),
        ),
        migrations.AddField(
            model_name='demandeabonnement',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('acompte_verse', 'Acompte versé'), ('en_cours', 'Paiements en cours'), ('solde', 'Soldé')], default='non_paye', max_length=20),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='equipements',
            field=models.JSONField(blank=True, default=list, help_text='Liste des équipements disponibles'),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='horaires_ouverture',
            field=models.JSONField(blank=True, default=dict, help_text="Horaires d'ouverture par jour"),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='montant_acompte_fixe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant fixe d'acompte en FCFA (alternatif au pourcentage)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='orange_money_number',
            field=models.CharField(blank=True, help_text='Numéro Orange Money du gestionnaire', max_length=20),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='pourcentage_acompte',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text="Pourcentage d'acompte requis (ex: 30.00 pour 30%)", max_digits=5),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='type_acompte',
            field=models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], default='pourcentage', help_text="Type d'acompte requis", max_length=20),
        ),
        migrations.AddField(
            model_name='terrainsynthetiquesdakar',
            name='wave_payment_link',
            field=models.URLField(blank=True, help_text='Lien Wave Business personnel du gestionnaire', max_length=500),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='duree_seance',
            field=models.PositiveIntegerField(default=1, help_text='Durée en heures'),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Paiement comptant'), ('par_match', 'Paiement par match (avec acompte)'), ('par_tranche', 'Paiement par tranche')], default='comptant', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='terrains.planabonnement'),
        ),
        migrations.AlterField(
            model_name='demandeabonnement',
            name='statut',
            field=models.CharField(choices=[('pending_manager', 'En attente gestionnaire'), ('pending_payment', 'En attente paiement'), ('active', 'Active'), ('refused', 'Refusée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending_manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='terrainsynthetiquesdakar',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='terrainsynthetiquesdakar',
            name='image_principale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='terrainsynthetiquesdakar',
            name='nombre_joueurs',
            field=models.CharField(default='5v5', help_text='Format(s) de jeu, ex: "5v5, 7v7"', max_length=100),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('reservation', 'Réservation'), ('abonnement', 'Abonnement'), ('mixte', 'Mixte')], default='mixte', help_text='Source des revenus', max_length=20)),
                ('periode', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('date_debut_periode', models.DateField(help_text='Début de la période de calcul')),
                ('date_fin_periode', models.DateField(help_text='Fin de la période de calcul')),
                ('montant_revenus_reservations', models.DecimalField(decimal_places=2, default=0, help_text='Revenus réservations', max_digits=12)),
                ('montant_revenus_abonnements', models.DecimalField(decimal_places=2, default=0, help_text='Revenus abonnements', max_digits=12)),
                ('montant_revenus', models.DecimalField(decimal_places=2, default=0, help_text='Revenus totaux sur la période', max_digits=12)),
                ('nb_reservations', models.PositiveIntegerField(default=0, help_text='Nombre de réservations')),
                ('nb_abonnements', models.PositiveIntegerField(default=0, help_text="Nombre d'abonnements")),
                ('taux_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Taux en %', max_digits=5)),
                ('montant_commission', models.DecimalField(decimal_places=2, default=0, help_text='Montant de la commission', max_digits=12)),
                ('statut', models.CharField(choices=[('due', 'Due'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='due', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('reference_paiement', models.CharField(blank=True, default='', help_text='Référence Wave/OM', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('gestionnaire', models.ForeignKey(help_text='Gestionnaire qui doit la commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions_dues', to=settings.AUTH_USER_MODEL)),
                ('terrain', models.ForeignKey(blank=True, help_text='Terrain concerné (optionnel si commission globale)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='terrains.terrainsynthetiquesdakar')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-date_fin_periode'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type_paiement', models.CharField(choices=[('acompte', 'Acompte'), ('seance', 'Paiement séance'), ('tranche', 'Tranche'), ('solde', 'Solde final')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('numero_seance', models.PositiveIntegerField(blank=True, help_text='Numéro de séance si paiement par match', null=True)),
                ('reference_paiement', models.CharField(blank=True, default='', help_text='Référence Wave/OM', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='terrains.demandeabonnement')),
            ],
            options={
                'db_table': 'paiements_abonnement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
