# Generated by Django 5.0.3 on 2026-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrains', '0007_demandeabonnement_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='taux_commission',
            field=models.IntegerField(default=10, help_text='Taux en %'),
        ),
    ]
